// apps/app1-java-react/frontend/src/App.tsx
import { useEffect, useState } from "react";

const FRONTEND_VERSION = __APP_VERSION__;

interface Item {
  id: number;
  name: string;
  note: string;
}

export function App() {
  const [backendVersion, setBackendVersion] = useState<string | null>(null);
  const [items, setItems] = useState<Item[]>([]);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetch("/api/v1/version")
      .then((r) => (r.ok ? r.json() : Promise.reject(r.status)))
      .then((d) => setBackendVersion(d.version))
      .catch((e) => setError(String(e)));

    fetch("/api/v1/items")
      .then((r) => (r.ok ? r.json() : Promise.reject(r.status)))
      .then(setItems)
      .catch((e) => setError(String(e)));
  }, []);

  return (
    <main style={{ fontFamily: "sans-serif", padding: "2rem" }}>
      <h1>app1-java-react</h1>
      <p>Фронт: React + Vite. Бек: Spring Boot.</p>
      <ul>
        <li>Версия фронта 123456: <b>{FRONTEND_VERSION}</b></li>
        <li>
          Версия бека (через REST):{" "}
          <b>{backendVersion ?? (error ? `ошибка: ${error}` : "загрузка…")}</b>
        </li>
      </ul>

      <h2>Записи из БД (таблица items)</h2>
      {error && <p style={{ color: "crimson" }}>Ошибка: {error}</p>}
      <table border={1} cellPadding={6} style={{ borderCollapse: "collapse" }}>
        <thead>
          <tr><th>id</th><th>name</th><th>note</th></tr>
        </thead>
        <tbody>
          {items.map((it) => (
            <tr key={it.id}>
              <td>{it.id}</td>
              <td>{it.name}</td>
              <td>{it.note}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </main>
  );
}

// apps/app2-python-angular/frontend/src/app/app.component.ts
import { Component, signal } from "@angular/core";
import { HttpClient } from "@angular/common/http";
import { version as frontendVersion } from "../../package.json";

interface Item {
  id: number;
  name: string;
  note: string;
}

@Component({
  selector: "app-root",
  standalone: true,
  template: `
    <main style="font-family: sans-serif; padding: 2rem;">
      <h1>app2-python-angular</h1>
      <p>Фронт: Angular. Бек: FastAPI.</p>
      <ul>
        <li>Версия фронта: <b>{{ frontendVersion }}</b></li>
        <li>Версия бека (через REST): <b>{{ backendVersion() }}</b></li>
      </ul>

      <h2>Записи из БД (таблица items)</h2>
      <table border="1" cellpadding="6" style="border-collapse: collapse;">
        <thead>
          <tr><th>id</th><th>name</th><th>note</th></tr>
        </thead>
        <tbody>
          @for (it of items(); track it.id) {
            <tr>
              <td>{{ it.id }}</td>
              <td>{{ it.name }}</td>
              <td>{{ it.note }}</td>
            </tr>
          }
        </tbody>
      </table>
    </main>
  `,
})
export class AppComponent {
  frontendVersion = frontendVersion;
  backendVersion = signal("загрузка…");
  items = signal<Item[]>([]);

  constructor(http: HttpClient) {
    http.get<{ version: string }>("/api/v1/version").subscribe({
      next: (d) => this.backendVersion.set(d.version),
      error: (e) => this.backendVersion.set("ошибка: " + e.status),
    });
    http.get<Item[]>("/api/v1/items").subscribe({
      next: (d) => this.items.set(d),
      error: () => this.items.set([]),
    });
  }
}
